name: ALT-APPS-API CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      #max-parallel: 1
      matrix:
        node-version: [20.x, 22.x, 24.x]
        mongodb-version: ["6.0", "7.0", "8.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Fetch entire repository contents

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      # Spin up MongoDB Docker instance in GitHub Actions
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.API}}" >> .env

      - name: NPM install, build and test
        run: |
          npm install
          npm run build
          npm run pwTest
          npm run failTest
